### ISSUE TITLE
Can't get Catch function working

### ISSUE THREAD

**Issue by Gazoney** [Tishj/VortexBot#4]
Hi there, I'm having some trouble getting the catch functionality to work, when attempting to run it, it will get to the point where the map opens, which I then run into the following:
 `Traceback (most recent call last):
  File "C:\Users\calni\Documents\VortexBot-main\VortexBot-main\vortexbot.py", line 814, in <module>
    player.gotta_catch_em_all()
  File "C:\Users\calni\Documents\VortexBot-main\VortexBot-main\vortexbot.py", line 263, in gotta_catch_em_all
    if evaluate_pokemon_info(mutex, pokefound, [""]):
  File "C:\Users\calni\Documents\VortexBot-main\VortexBot-main\vortexbot.py", line 104, in evaluate_pokemon_info
    encounter = driver.execute_script('return Phaser.Display.Canvas.CanvasPool.pool[2].parent.scene.encounterProfile.encounter;')
  File "C:\Users\calni\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0a7-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 759, in execute_script
    return self.execute(command, {
  File "C:\Users\calni\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0a7-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 368, in execute
    self.error_handler.check_response(response)
  File "C:\Users\calni\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-4.0.0a7-py3.9.egg\selenium\webdriver\remote\errorhandler.py", line 240, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot create proxy with a non-object as target or handler
  (Session info: chrome=90.0.4430.85)
Stacktrace:
Backtrace:
        Ordinal0 [0x00E1C013+2474003]
        Ordinal0 [0x00DB29C1+2042305]
        Ordinal0 [0x00CC2F68+1060712]
        Ordinal0 [0x00CC542E+1070126]
        Ordinal0 [0x00CC5C33+1072179]
        Ordinal0 [0x00D15F4C+1400652]
        Ordinal0 [0x00D06813+1337363]
        Ordinal0 [0x00D155CB+1398219]
        Ordinal0 [0x00D066DB+1337051]
        Ordinal0 [0x00CE3427+1192999]
        Ordinal0 [0x00CE42EE+1196782]
        Ordinal0 [0x00CE4279+1196665]
        GetHandleVerifier [0x00FA96FC+1590332]
        GetHandleVerifier [0x01058614+2306900]
        GetHandleVerifier [0x00EA9E93+543699]
        GetHandleVerifier [0x00EA92CE+540686]
        Ordinal0 [0x00DB86BA+2066106]
        Ordinal0 [0x00DBD1C8+2085320]
        Ordinal0 [0x00DBD308+2085640]
        Ordinal0 [0x00DC67F3+2123763]
        BaseThreadInitThunk [0x758CFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77477C7E+286]
        RtlGetAppContainerNamedObjectPath [0x77477C4E+238]`

**Comment by tolgahantunc** [comment]
Hi, yes, I am encountering the same. I did a small change in the code, and commented function evaluate_pokemon_info() in vortexbot.py. The function just returns false which means the bot cannot understand if there is a new pokemon or not. 

@Tishj, can you please take a look at line 104 in vortexbot.py? 
encounter = driver.execute_script('return Phaser.Display.Canvas.CanvasPool.pool[2].parent.scene.encounterProfile.encounter;')

This is throwing the error mentioned above.

**Comment by Tishj** [comment]
`Message: javascript error: Cannot create proxy with a non-object as target or handler`
This is due to the new code pokemon vortex added that I mentioned in #7, `encounter` is undefined here
and it tries to create a Proxy around something that isn't defined
